INSERT INTO [dbo].[Type] ([Name],[Description]) VALUES ('Amber Ale','Amber Ale')
INSERT INTO [dbo].[Type] ([Name],[Description]) VALUES ('American Amber Lager','American Amber Lager')
INSERT INTO [dbo].[Type] ([Name],[Description]) VALUES ('American Brown Ale','American Brown Ale')
INSERT INTO [dbo].[Type] ([Name],[Description]) VALUES ('American Strong Ale','American Strong Ale')
INSERT INTO [dbo].[Type] ([Name],[Description]) VALUES ('Black Lager','Black Lager')
INSERT INTO [dbo].[Type] ([Name],[Description]) VALUES ('Brown Ale','Brown Ale')
INSERT INTO [dbo].[Type] ([Name],[Description]) VALUES ('India Pale Ale','India Pale Ale')
INSERT INTO [dbo].[Type] ([Name],[Description]) VALUES ('India Pale Lager','India Pale Lager')
INSERT INTO [dbo].[Type] ([Name],[Description]) VALUES ('Irish Dry Stout','Irish Dry Stout')
INSERT INTO [dbo].[Type] ([Name],[Description]) VALUES ('Lager','Lager')
INSERT INTO [dbo].[Type] ([Name],[Description]) VALUES ('Pale Ale','Pale Ale')
INSERT INTO [dbo].[Type] ([Name],[Description]) VALUES ('Pale Lager','Pale Lager')
INSERT INTO [dbo].[Type] ([Name],[Description]) VALUES ('Pilsner','Pilsner')
INSERT INTO [dbo].[Type] ([Name],[Description]) VALUES ('Porter','Porter')
INSERT INTO [dbo].[Type] ([Name],[Description]) VALUES ('Pumpkin','Pumpkin')
INSERT INTO [dbo].[Type] ([Name],[Description]) VALUES ('Fruit','Fruit')
INSERT INTO [dbo].[Type] ([Name],[Description]) VALUES ('White Ale','White Ale')


