//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SocialHeatMapModel", "FK_SearchHistory_User", "TBL_USER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SocialHeatMap.DataServices.TBL_USER), "TBL_SEARCH_HISTORY", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SocialHeatMap.DataServices.TBL_SEARCH_HISTORY), true)]

#endregion

namespace SocialHeatMap.DataServices
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SocialHeatMapEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SocialHeatMapEntities object using the connection string found in the 'SocialHeatMapEntities' section of the application configuration file.
        /// </summary>
        public SocialHeatMapEntities() : base("name=SocialHeatMapEntities", "SocialHeatMapEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SocialHeatMapEntities object.
        /// </summary>
        public SocialHeatMapEntities(string connectionString) : base(connectionString, "SocialHeatMapEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SocialHeatMapEntities object.
        /// </summary>
        public SocialHeatMapEntities(EntityConnection connection) : base(connection, "SocialHeatMapEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBL_USER> TBL_USER
        {
            get
            {
                if ((_TBL_USER == null))
                {
                    _TBL_USER = base.CreateObjectSet<TBL_USER>("TBL_USER");
                }
                return _TBL_USER;
            }
        }
        private ObjectSet<TBL_USER> _TBL_USER;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBL_COORDS> TBL_COORDS
        {
            get
            {
                if ((_TBL_COORDS == null))
                {
                    _TBL_COORDS = base.CreateObjectSet<TBL_COORDS>("TBL_COORDS");
                }
                return _TBL_COORDS;
            }
        }
        private ObjectSet<TBL_COORDS> _TBL_COORDS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TBL_SEARCH_HISTORY> TBL_SEARCH_HISTORY
        {
            get
            {
                if ((_TBL_SEARCH_HISTORY == null))
                {
                    _TBL_SEARCH_HISTORY = base.CreateObjectSet<TBL_SEARCH_HISTORY>("TBL_SEARCH_HISTORY");
                }
                return _TBL_SEARCH_HISTORY;
            }
        }
        private ObjectSet<TBL_SEARCH_HISTORY> _TBL_SEARCH_HISTORY;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBL_USER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBL_USER(TBL_USER tBL_USER)
        {
            base.AddObject("TBL_USER", tBL_USER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBL_COORDS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBL_COORDS(TBL_COORDS tBL_COORDS)
        {
            base.AddObject("TBL_COORDS", tBL_COORDS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TBL_SEARCH_HISTORY EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTBL_SEARCH_HISTORY(TBL_SEARCH_HISTORY tBL_SEARCH_HISTORY)
        {
            base.AddObject("TBL_SEARCH_HISTORY", tBL_SEARCH_HISTORY);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SocialHeatMapModel", Name="TBL_COORDS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_COORDS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBL_COORDS object.
        /// </summary>
        /// <param name="cOORD_ID">Initial value of the COORD_ID property.</param>
        /// <param name="lATITUDE">Initial value of the LATITUDE property.</param>
        /// <param name="lONGITUDE">Initial value of the LONGITUDE property.</param>
        public static TBL_COORDS CreateTBL_COORDS(global::System.Int32 cOORD_ID, global::System.Decimal lATITUDE, global::System.Decimal lONGITUDE)
        {
            TBL_COORDS tBL_COORDS = new TBL_COORDS();
            tBL_COORDS.COORD_ID = cOORD_ID;
            tBL_COORDS.LATITUDE = lATITUDE;
            tBL_COORDS.LONGITUDE = lONGITUDE;
            return tBL_COORDS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 COORD_ID
        {
            get
            {
                return _COORD_ID;
            }
            set
            {
                if (_COORD_ID != value)
                {
                    OnCOORD_IDChanging(value);
                    ReportPropertyChanging("COORD_ID");
                    _COORD_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("COORD_ID");
                    OnCOORD_IDChanged();
                }
            }
        }
        private global::System.Int32 _COORD_ID;
        partial void OnCOORD_IDChanging(global::System.Int32 value);
        partial void OnCOORD_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal LATITUDE
        {
            get
            {
                return _LATITUDE;
            }
            set
            {
                OnLATITUDEChanging(value);
                ReportPropertyChanging("LATITUDE");
                _LATITUDE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LATITUDE");
                OnLATITUDEChanged();
            }
        }
        private global::System.Decimal _LATITUDE;
        partial void OnLATITUDEChanging(global::System.Decimal value);
        partial void OnLATITUDEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal LONGITUDE
        {
            get
            {
                return _LONGITUDE;
            }
            set
            {
                OnLONGITUDEChanging(value);
                ReportPropertyChanging("LONGITUDE");
                _LONGITUDE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LONGITUDE");
                OnLONGITUDEChanged();
            }
        }
        private global::System.Decimal _LONGITUDE;
        partial void OnLONGITUDEChanging(global::System.Decimal value);
        partial void OnLONGITUDEChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SocialHeatMapModel", Name="TBL_SEARCH_HISTORY")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_SEARCH_HISTORY : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBL_SEARCH_HISTORY object.
        /// </summary>
        /// <param name="sEARCH_ID">Initial value of the SEARCH_ID property.</param>
        /// <param name="uSER_ID">Initial value of the USER_ID property.</param>
        /// <param name="sEACH_TEXT">Initial value of the SEACH_TEXT property.</param>
        /// <param name="rESULTS">Initial value of the RESULTS property.</param>
        /// <param name="cREATED_DT">Initial value of the CREATED_DT property.</param>
        public static TBL_SEARCH_HISTORY CreateTBL_SEARCH_HISTORY(global::System.Int32 sEARCH_ID, global::System.Int32 uSER_ID, global::System.String sEACH_TEXT, global::System.String rESULTS, global::System.DateTime cREATED_DT)
        {
            TBL_SEARCH_HISTORY tBL_SEARCH_HISTORY = new TBL_SEARCH_HISTORY();
            tBL_SEARCH_HISTORY.SEARCH_ID = sEARCH_ID;
            tBL_SEARCH_HISTORY.USER_ID = uSER_ID;
            tBL_SEARCH_HISTORY.SEACH_TEXT = sEACH_TEXT;
            tBL_SEARCH_HISTORY.RESULTS = rESULTS;
            tBL_SEARCH_HISTORY.CREATED_DT = cREATED_DT;
            return tBL_SEARCH_HISTORY;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SEARCH_ID
        {
            get
            {
                return _SEARCH_ID;
            }
            set
            {
                if (_SEARCH_ID != value)
                {
                    OnSEARCH_IDChanging(value);
                    ReportPropertyChanging("SEARCH_ID");
                    _SEARCH_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SEARCH_ID");
                    OnSEARCH_IDChanged();
                }
            }
        }
        private global::System.Int32 _SEARCH_ID;
        partial void OnSEARCH_IDChanging(global::System.Int32 value);
        partial void OnSEARCH_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 USER_ID
        {
            get
            {
                return _USER_ID;
            }
            set
            {
                OnUSER_IDChanging(value);
                ReportPropertyChanging("USER_ID");
                _USER_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("USER_ID");
                OnUSER_IDChanged();
            }
        }
        private global::System.Int32 _USER_ID;
        partial void OnUSER_IDChanging(global::System.Int32 value);
        partial void OnUSER_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SEACH_TEXT
        {
            get
            {
                return _SEACH_TEXT;
            }
            set
            {
                OnSEACH_TEXTChanging(value);
                ReportPropertyChanging("SEACH_TEXT");
                _SEACH_TEXT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SEACH_TEXT");
                OnSEACH_TEXTChanged();
            }
        }
        private global::System.String _SEACH_TEXT;
        partial void OnSEACH_TEXTChanging(global::System.String value);
        partial void OnSEACH_TEXTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RESULTS
        {
            get
            {
                return _RESULTS;
            }
            set
            {
                OnRESULTSChanging(value);
                ReportPropertyChanging("RESULTS");
                _RESULTS = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RESULTS");
                OnRESULTSChanged();
            }
        }
        private global::System.String _RESULTS;
        partial void OnRESULTSChanging(global::System.String value);
        partial void OnRESULTSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CREATED_DT
        {
            get
            {
                return _CREATED_DT;
            }
            set
            {
                OnCREATED_DTChanging(value);
                ReportPropertyChanging("CREATED_DT");
                _CREATED_DT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_DT");
                OnCREATED_DTChanged();
            }
        }
        private global::System.DateTime _CREATED_DT;
        partial void OnCREATED_DTChanging(global::System.DateTime value);
        partial void OnCREATED_DTChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SocialHeatMapModel", "FK_SearchHistory_User", "TBL_USER")]
        public TBL_USER TBL_USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBL_USER>("SocialHeatMapModel.FK_SearchHistory_User", "TBL_USER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBL_USER>("SocialHeatMapModel.FK_SearchHistory_User", "TBL_USER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBL_USER> TBL_USERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBL_USER>("SocialHeatMapModel.FK_SearchHistory_User", "TBL_USER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBL_USER>("SocialHeatMapModel.FK_SearchHistory_User", "TBL_USER", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SocialHeatMapModel", Name="TBL_USER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_USER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TBL_USER object.
        /// </summary>
        /// <param name="uSER_ID">Initial value of the USER_ID property.</param>
        /// <param name="fIRST_NAME">Initial value of the FIRST_NAME property.</param>
        /// <param name="lAST_NAME">Initial value of the LAST_NAME property.</param>
        /// <param name="sCREENNAME">Initial value of the SCREENNAME property.</param>
        /// <param name="iS_ADMIN">Initial value of the IS_ADMIN property.</param>
        /// <param name="cREATED_DT">Initial value of the CREATED_DT property.</param>
        /// <param name="aCCESS_TOKEN">Initial value of the ACCESS_TOKEN property.</param>
        /// <param name="aCCESS_TOKEN_SECRET">Initial value of the ACCESS_TOKEN_SECRET property.</param>
        public static TBL_USER CreateTBL_USER(global::System.Int32 uSER_ID, global::System.String fIRST_NAME, global::System.String lAST_NAME, global::System.String sCREENNAME, global::System.Boolean iS_ADMIN, global::System.DateTime cREATED_DT, global::System.String aCCESS_TOKEN, global::System.String aCCESS_TOKEN_SECRET)
        {
            TBL_USER tBL_USER = new TBL_USER();
            tBL_USER.USER_ID = uSER_ID;
            tBL_USER.FIRST_NAME = fIRST_NAME;
            tBL_USER.LAST_NAME = lAST_NAME;
            tBL_USER.SCREENNAME = sCREENNAME;
            tBL_USER.IS_ADMIN = iS_ADMIN;
            tBL_USER.CREATED_DT = cREATED_DT;
            tBL_USER.ACCESS_TOKEN = aCCESS_TOKEN;
            tBL_USER.ACCESS_TOKEN_SECRET = aCCESS_TOKEN_SECRET;
            return tBL_USER;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 USER_ID
        {
            get
            {
                return _USER_ID;
            }
            set
            {
                if (_USER_ID != value)
                {
                    OnUSER_IDChanging(value);
                    ReportPropertyChanging("USER_ID");
                    _USER_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("USER_ID");
                    OnUSER_IDChanged();
                }
            }
        }
        private global::System.Int32 _USER_ID;
        partial void OnUSER_IDChanging(global::System.Int32 value);
        partial void OnUSER_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FIRST_NAME
        {
            get
            {
                return _FIRST_NAME;
            }
            set
            {
                OnFIRST_NAMEChanging(value);
                ReportPropertyChanging("FIRST_NAME");
                _FIRST_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FIRST_NAME");
                OnFIRST_NAMEChanged();
            }
        }
        private global::System.String _FIRST_NAME;
        partial void OnFIRST_NAMEChanging(global::System.String value);
        partial void OnFIRST_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LAST_NAME
        {
            get
            {
                return _LAST_NAME;
            }
            set
            {
                OnLAST_NAMEChanging(value);
                ReportPropertyChanging("LAST_NAME");
                _LAST_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LAST_NAME");
                OnLAST_NAMEChanged();
            }
        }
        private global::System.String _LAST_NAME;
        partial void OnLAST_NAMEChanging(global::System.String value);
        partial void OnLAST_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SCREENNAME
        {
            get
            {
                return _SCREENNAME;
            }
            set
            {
                OnSCREENNAMEChanging(value);
                ReportPropertyChanging("SCREENNAME");
                _SCREENNAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SCREENNAME");
                OnSCREENNAMEChanged();
            }
        }
        private global::System.String _SCREENNAME;
        partial void OnSCREENNAMEChanging(global::System.String value);
        partial void OnSCREENNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IS_ADMIN
        {
            get
            {
                return _IS_ADMIN;
            }
            set
            {
                OnIS_ADMINChanging(value);
                ReportPropertyChanging("IS_ADMIN");
                _IS_ADMIN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IS_ADMIN");
                OnIS_ADMINChanged();
            }
        }
        private global::System.Boolean _IS_ADMIN;
        partial void OnIS_ADMINChanging(global::System.Boolean value);
        partial void OnIS_ADMINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CREATED_DT
        {
            get
            {
                return _CREATED_DT;
            }
            set
            {
                OnCREATED_DTChanging(value);
                ReportPropertyChanging("CREATED_DT");
                _CREATED_DT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CREATED_DT");
                OnCREATED_DTChanged();
            }
        }
        private global::System.DateTime _CREATED_DT;
        partial void OnCREATED_DTChanging(global::System.DateTime value);
        partial void OnCREATED_DTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ACCESS_TOKEN
        {
            get
            {
                return _ACCESS_TOKEN;
            }
            set
            {
                OnACCESS_TOKENChanging(value);
                ReportPropertyChanging("ACCESS_TOKEN");
                _ACCESS_TOKEN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ACCESS_TOKEN");
                OnACCESS_TOKENChanged();
            }
        }
        private global::System.String _ACCESS_TOKEN;
        partial void OnACCESS_TOKENChanging(global::System.String value);
        partial void OnACCESS_TOKENChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ACCESS_TOKEN_SECRET
        {
            get
            {
                return _ACCESS_TOKEN_SECRET;
            }
            set
            {
                OnACCESS_TOKEN_SECRETChanging(value);
                ReportPropertyChanging("ACCESS_TOKEN_SECRET");
                _ACCESS_TOKEN_SECRET = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ACCESS_TOKEN_SECRET");
                OnACCESS_TOKEN_SECRETChanged();
            }
        }
        private global::System.String _ACCESS_TOKEN_SECRET;
        partial void OnACCESS_TOKEN_SECRETChanging(global::System.String value);
        partial void OnACCESS_TOKEN_SECRETChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SocialHeatMapModel", "FK_SearchHistory_User", "TBL_SEARCH_HISTORY")]
        public EntityCollection<TBL_SEARCH_HISTORY> TBL_SEARCH_HISTORY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBL_SEARCH_HISTORY>("SocialHeatMapModel.FK_SearchHistory_User", "TBL_SEARCH_HISTORY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBL_SEARCH_HISTORY>("SocialHeatMapModel.FK_SearchHistory_User", "TBL_SEARCH_HISTORY", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
